api:
  dashboard: true
  insecure: true

entryPoints:
  websecure: 
    address: ":443" 

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
  file:
    directory: /etc/traefik/cert-config
    watch: true

metrics:
  prometheus: {}

log:
  level: INFO
