---
- name: Run Common Role
  hosts: the-ocean
  become: true
  vars_prompt:
    - name: SSILVER_PASSWORD
      prompt: "Enter the password for ssilver user"
      private: yes
  vars:
    distribution_codename: bookworm 
    server_architecture: amd64
  roles:
    - common
  tags:
    - common
    - utilities
    - docker
    - users
