---
- name: Ensure /repos directory exists
  file:
    path: "/repos/{{ repo_name }}"
    state: directory
    mode: '0755'

- name: Clone repository if it does not exist
  git:
    repo: "{{ repo_url }}"
    dest: "/repos/{{ repo_name }}"
    version: "{{ repo_version }}"
    force: yes
  when: not repo_exists.stat.exists

- name: Pull latest changes if repository already exists
  git:
    repo: "{{ repo_url }}"
    dest: "/repos/{{ repo_name }}"
    version: "{{ repo_version }}"
    force: yes
    update: yes
  when: repo_exists.stat.exists

