api:
  dashboard: true
  debug: true
entryPoints:
  http: 
    address: ":80"
  https: 
    address: ":443" 
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    tls:
      cert: /etc/traefik/samsilver.ca.pem
      key: /etc/traefik/private-key.pem
