---
- name: Get db of users
  getent:
    database: passwd
  
- name: Create user ssilver with home directory
  become: true
  user:
    name: ssilver
    groups: sudo
    password: "{{ SSILVER_PASSWORD | password_hash('sha512') }}"
    shell: /usr/bin/fish
  when: not ( "ssilver" in getent_passwd.keys() )

- name: Create .ssh directory in ssilver's home
  become: true
  file:
    path: /home/ssilver/.ssh
    state: directory
    owner: ssilver
    group: ssilver
    mode: '0700'

- name: Check if authorized_keys file exists
  stat:
    path: "/home/ssilver/.ssh/authorized_keys"
  register: authorized_keys_stat

- name: Copy root's authorized_keys to ssilver user
  become: true
  copy:
    src: /root/.ssh/authorized_keys
    dest: /home/ssilver/.ssh/authorized_keys
    owner: ssilver
    group: ssilver
    mode: '0600'
  when: not authorized_keys_stat 

- name: Check if dotfiles exists
  stat:
    path: "/home/ssilver/dotfiles"
  register: dotfiles_stat
  
- name: Clone GitHub repository
  git:
    repo: "https://github.com/sam55silver/dotfiles.git"
    dest: "/home/ssilver/dotfiles"
  when: dotfiles_status.stat.exists is not defined or not dotfiles_status.stat.exists
  become: yes
  become_user: ssilver

- name: Copy contents of config directory
  copy:
    src: "/home/ssilver/dotfiles/"
    dest: "/home/ssilver/.config/"
    owner: ssilver
    group: ssilver
    remote_src: yes
  when: dotfiles_status.stat.exists is not defined or not dotfiles_status.stat.exists
  become: yes
  become_user: ssilver
