---
- name: Check if ssilver user exists
  become: true
  shell: getent passwd ssilver
  register: ssilver_user_check
  changed_when: false
  ignore_errors: true
  tags:
    - users

- name: Create group docker
  group:
    name: docker
    state: present
  when: ssilver_user_check.rc != 0
  become: yes
  tags:
    - users

- name: Create user ssilver with home directory
  become: true
  user:
    name: ssilver
    groups: sudo,docker
    password: "{{ SSILVER_PASSWORD | password_hash('sha512') }}"
    shell: /usr/bin/fish
  when: ssilver_user_check.rc != 0
  tags:
    - users

- name: Create .ssh directory in ssilver's home
  become: true
  file:
    path: /home/ssilver/.ssh
    state: directory
    owner: ssilver
    group: ssilver
    mode: '0700'
  tags:
    - users

- name: Check if authorized_keys file exists
  stat:
    path: "/home/ssilver/.ssh/authorized_keys"
  register: authorized_keys_stat

- name: Copy root's authorized_keys to ssilver user
  become: true
  copy:
    src: /root/.ssh/authorized_keys
    dest: /home/ssilver/.ssh/authorized_keys
    owner: ssilver
    group: ssilver
    mode: '0600'
  when: not authorized_keys_stat 
  tags:
    - users

- name: Check if dotfiles exists
  stat:
    path: "/home/ssilver/dotfiles"
  register: dotfiles_stat
  tags:
    - users
  
- name: Clone GitHub repository
  git:
    repo: "https://github.com/sam55silver/dotfiles.git"
    dest: "/home/ssilver/dotfiles"
  when: dotfiles_status.stat.exists is not defined or not dotfiles_status.stat.exists
  become: yes
  become_user: ssilver
  tags:
    - users

- name: Copy contents of config directory
  copy:
    src: "/home/ssilver/dotfiles/config/"
    dest: "/home/ssilver/.config/"
    owner: ssilver
    group: ssilver
    remote_src: yes
  when: dotfiles_status.stat.exists is not defined or not dotfiles_status.stat.exists
  become: yes
  become_user: ssilver
  tags:
    - users

- name: Create directory for docker configs
  become: true
  file:
    path: /home/ssilver/configs
    owner: ssilver
    group: docker
    state: directory

- name: Create directory for docker data
  become: true
  file:
    path: /home/ssilver/data
    owner: ssilver
    group: docker
    state: directory

- name: Create directory for certificates
  become: true
  file:
    path: /home/ssilver/certs
    owner: ssilver
    group: docker
    state: directory
