---
- name: Install Utility Packages
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - wget
      - vim
      - sudo
      - htop
      - fish
      - tmux
      - git
    state: present
    update_cache: true
