---
- name: Add Docker's official GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  tags:
    - docker

- name: Create directory for apt keyrings
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - docker

- name: Download Docker GPG key
  become: true
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  tags:
    - docker

- name: Add Docker repository to Apt sources
  become: true
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ server_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ distribution_codename }} stable"
    create: yes
  tags:
    - docker

- name: Install Docker packages
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes
  tags:
    - docker

- name: Enable and Start Docker service
  become: true
  systemd:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker

- name: Create directory for docker configs
  become: true
  file:
    path: /configs
    state: directory
  tags:
    - docker

- name: Create directory for docker data
  become: true
  file:
    path: /data
    state: directory
  tags:
    - docker
