---
- name: Create Grafana user
  become: true
  user:
    name: grafana
    create_home: false
  tags:
    - docker

- name: Create Grafana Data Directory
  become: true
  file:
    path: /data/grafana
    state: directory
    owner: grafana
    group: grafana
  tags:
    - docker

- name: Create Grafana Config Directory
  become: true
  file:
    path: /configs/grafana
    state: directory
    owner: grafana
    group: grafana
  tags:
    - docker

- name: Get Grafana UID
  shell: id -u grafana
  register: grafana_uid

- name: Get Grafana GID
  shell: id -g grafana
  register: grafana_gid

- name: Create Grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana:10.3.1
    ports: 3000:3000
    user: "{{ grafana_uid.stdout }}:{{ grafana_gid.stdout }}"
    volumes:
      - /data/grafana:/var/lib/grafana
    labels:
      traefik.http.routers.grafana.tls: "true"

- name: Create Traefik user
  become: true
  user:
    name: traefik
    groups: docker
    create_home: false
  tags:
    - docker

- name: Create Traefik Config Directory
  become: true
  file:
    path: /configs/traefik
    state: directory
    owner: traefik
    group: traefik
  tags:
    - docker

- name: Copy Traefik Config over
  copy:
    src: traefik.yml
    dest: /configs/traefik

- name: Get Traefik UID
  shell: id -u traefik
  register: traefik_uid

- name: Get Traefik GID
  shell: id -g traefik
  register: traefik_gid

- name: Create Traefik container
  community.docker.docker_container:
    name: traefik
    image: traefik:v2.10
    ports: 
      - 80:80
      - 443:443
    volumes:
      - /configs/traefik:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik.entrypoints: http
      traefik.http.routers.traefik.rule: Host(`traefik.samsilver.ca`)
      traefik.http.routers.traefik-secure.entrypoints: https
      traefik.http.routers.traefik-secure.rule: Host(`traefik.samsilver.ca`)
      traefik.http.routers.traefik-secure.tls: "true"
      traefik.http.routers.traefik-secure.tls.certificates[0].certFile: /ect/traefik/samsilver.ca.pem
      traefik.http.routers.traefik-secure.tls.certificates[0].keyFile: /ect/traefik/private-key.pem
      traefik.http.routers.traefik-secure.tls.domains[0].main: samsilver.ca
      traefik.http.routers.traefik-secure.tls.domains[0].sans: "*.samsilver.ca"
      traefik.http.routers.traefik-secure.tls.service: api@internal



