---
- name: Create directory for docker configs
  become: true
  file:
    path: /configs/docker
    owner: ssilver
    group: infra
    mode: '0755'
    state: directory

- name: Create directory for docker data
  become: true
  file:
    path: /data/docker
    owner: ssilver
    group: infra
    mode: '0755'
    state: directory
