---
- name: Install Docker Registry container
  docker_container:
    name: registry
    image: registry:latest
    state: started
    restart_policy: always
    published_ports:
      - "{{ image_registry_port }}:5000"
    volumes:
      - /data/docker/registry:/var/lib/registry
