---
- name: Ensure apache2-utils is installed
  apt:
    name: apache2-utils
    state: present

- name: Create auth directory
  file:
    path: "/configs/registry"
    owner: ssilver
    group: infra
    state: directory
    mode: '0755'

- name: Ensure the htpasswd file exists
  ansible.builtin.file:
    path: "/configs/registry/registry.password"
    state: touch
    mode: '0755'
    owner: ssilver
    group: docker

- name: Check if htpasswd file already exists
  ansible.builtin.stat:
    path: "/configs/registry/registry.password"
  register: htpasswd_file_check

- name: Create the htpasswd file with the provided user (only if file didn't exist before)
  ansible.builtin.command:
    cmd: htpasswd -Bbc /configs/registry/registry.password {{ registry_username }} {{ registry_password }}
  when: not htpasswd_file_check.stat.exists

- name: Create external Docker network
  community.docker.docker_network:
    name: web
    driver: bridge
    internal: no
    state: present

- name: Install Docker Registry container
  docker_container:
    name: registry
    image: registry:latest
    state: started
    restart_policy: always
    published_ports:
      - "5025:5000"
    volumes:
      - /data/registry:/var/lib/registry/docker/registry
      - /configs/registry:/auth
    labels:
      traefik.http.routers.registry.tls: "true"
      traefik.http.routers.registry.rule: "Host(`registry.samsilver.ca`)"
    env:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
    networks:
      - name: web
