---
- name: Build and Tag Docker Image to Registry
  hosts: localhost
  vars:
    registry_server: "registry.samsilver.ca"
  roles:
    - build

- name: Deploy Docker Image
  hosts: the-ocean
  remote_user: ssilver
  roles:
    - deployment
