---
- name: Setup Common Tools
  hosts: the-ocean
  become: true
  roles:
    - common
  tags:
    - common

- name: Setup Docker
  hosts: the-ocean
  become: true
  vars:
    distribution_codename: bookworm 
    server_architecture: amd64
    registry_username: ssilver
  vars_prompt:
    - name: registry_password
      prompt: "Enter the password for image registry"
      private: yes
  roles:
    - docker
  tags:
    - docker

- import_playbook: proxy.yml
